packages:
  - apps/*
  - packages/*

catalog:
  "@tailwindcss/postcss": 4.1.18
  "@types/node": 25.0.8
  "@types/react": 19.2.8
  "@types/react-dom": 19.2.3
  class-variance-authority: 0.7.1
  eslint: 9.39.2
  lucide-react: 0.562.0
  motion: 12.26.2
  next: 16.1.1
  next-themes: 0.4.6
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  yakuhanjp: 4.1.1
